[package]
name = "aoc-4"
version = "0.1.0"
authors = ["Sam Kirby <sam.kirby94@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-lib = { path = "../aoc-lib" }
once_cell = "1.5"
regex = "1"
